version: '3.9'

services:
  ntp:
    build: .
    image: ghcr.io/loganjohnlong/docker-nts-cloudflare:main
    container_name: nts-cloudflare
    restart: always
    ports:
      - 123:123/udp
    environment:
      - LOG_LEVEL=0
#      - TZ=America/Chicago
#      - NOCLIENTLOG=true
